# Generated by Django 4.2.11 on 2024-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="id",),
        migrations.AlterField(
            model_name="author",
            name="username",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="story", name="date", field=models.DateField(),
        ),
    ]
