# Generated by Django 4.2.11 on 2024-03-22 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0002_remove_author_id_alter_author_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
