# Generated by Django 4.2.11 on 2024-03-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0009_alter_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
