# Generated by Django 4.2.11 on 2024-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0010_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
